apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ymrz0bgvc-go 
  janus-idp.io/tekton: ymrz0bgvc-go
  backstage.io/kubernetes-id: ymrz0bgvc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ymrz0bgvc-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml