apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ymrz0bgvc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ymrz0bgvc-go 
  name: ymrz0bgvc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ymrz0bgvc-go 
